parameters:  
  webAppName: ''
  connectionString: ''
  productionEnv: false
  azureSubs: ''
  environment: '' 
  artifactFile: ''


  
jobs:
  - deployment: DeployInfraestructureDev
    displayName: "Deploy Infraestructure and App to Dev"
    environment: ${{parameters.environment}}
    pool:
      vmImage: windows-latest   
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              displayName: 'Download the build artifacts'
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'drop'
                downloadPath: '$(build.ArtifactStagingDirectory)'

            - task: AzureRmWebAppDeployment@4
              displayName: 'Azure App Service Deploy APAP BE'
              inputs:
                azureSubscription: '${{parameters.azureSubs}}'
                WebAppName: '${{parameters.webAppName}}'
                packageForLinux: '$(build.ArtifactStagingDirectory)/drop/${{parameters.artifactFile}}'
              condition: and(succeeded(), eq('${{parameters.productionEnv}}',false))
              
              

              